### ISSUE TITLE
Throws unexpected error when opening HTML

### ISSUE THREAD

**Issue by iamjawa** [trubitsyn/idea-carbon-now-sh#1]
When attempting to open the following code from PHPStorm with the plugin:

`    <table align="center" class="headcontainer" width="100%" height="33%">
        <tbody>
            <tr>
                <td>All the rows go here!</td>
            </tr>
        </tbody>
    </table> `

The carbon.now.sh URL opened throws the message "An unexpected error has occurred."

This code with the plugin is opened in the URL: https://carbon.now.sh/?bg=rgba(0,0,0,0)&t=dracula&l=auto&ds=true&wc=true&wa=true&pv=43px&ph=57px&ln=false&code=%20%20%20%20%3Ctable%20align%3D%22center%22%20class%3D%22headcontainer%22%20width%3D%22100%25%22%20height%3D%2233%25%22%3E%0A%20%20%20%20%20%20%20%20%3Ctbody%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EAll%20the%20rows%20go%20here!%3C%2Ftd%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%0A%20%20%20%20%20%20%20%20%3C%2Ftbody%3E%0A%20%20%20%20%3C%2Ftable%3E

However, when pasting the code directly into carbon.now.sh, no such error is thrown.

**Comment by trubitsyn** [comment]
Hello, thanks for the report. I'll try to fix it today.

**Comment by trubitsyn** [comment]
@iamjawa fixed in 1.0.3, will be available soon.

**Comment by iamjawa** [comment]
Look forward to it!
