### ISSUE TITLE
lose a Carbon settings

### ISSUE THREAD

**Issue by liangjingkanji** [trubitsyn/idea-carbon-now-sh#11]
I am  already logged

**Comment by trubitsyn** [comment]
@liangjingkanji, hello! Can't understand what "I am already logged" means. Could you please specify your problem?

**Comment by liangjingkanji** [comment]
I have already landed, But using this plugin to lose the configuration

**Comment by trubitsyn** [comment]
If you are talking about Carbon's "Sign In" feature: the plugin is neither supposed to keep nor read user settings currently - that should be done by Carbon itself. But being logged in, I was unable to get same Carbon settings in in a separate browser tab without uploading them manually. So, I guess, you should open an issue on the Carbon's issue tracker.
